### ISSUE TITLE
cant find surat when use geocoding???

### ISSUE THREAD

**Issue by regonyt** [neursh/open-meteo-dart#6]
i cant find anything i tried surat and no result pls fix

**Comment by regonyt** [comment]
pls help

**Comment by neursh** [comment]
The Geocoding API argument typo has been fixed since version 1.0.6. Please double-check and update the package.

If you're on the latest version, please provide an example replicating the issue.

**Comment by regonyt** [comment]
it dont work, furry dumb shit. ur trash. your package is trash. i have other

**Comment by neursh** [comment]
Prithee, kind sir, thou hast left behind this possession of thine. In mine humble and earnest duty, I am compelled to restore unto thee that which thou hast inadvertently forsaken. Mayhap it was left in haste or by some misfortune, but lo, it is now returned to thee, as is fitting and proper.
↓
![flame thrower](https://github.com/user-attachments/assets/558e4ebe-a92a-4cea-b19b-7580572c7c22)

**Comment by neursh** [comment]
Prithee, kind sir, thou hast left behind this possession of thine. In mine humble and earnest duty, I am compelled to restore unto thee that which thou hast inadvertently forsaken. Mayhaps it was left in haste or by some misfortune, but lo, it is now returned to thee, as is fitting and proper.
↓
![flame thrower](https://github.com/user-attachments/assets/558e4ebe-a92a-4cea-b19b-7580572c7c22)
